name: Python application

on:
push:
branches: [ "main" ]

permissions:
contents: read

jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Set up Python 3.10
- uses: actions/setup-python@v3
- name: Install dependencies
run: |
python -m pip install --upgrade pip
pip install aes-encryption
- name: Test Execution
run: |
cat teste.txt
pip encrypt.py
cat teste.txt
pip decrypt.py
